export const PROFILE_TITLE = 'Profile Management'
export const PROFILE_HOME_TAB_TITLE = 'Home'
export const PROFILE_PERSONAL_TAB_TITLE = 'Personal'
export const PROFILE_SECURITY_TAB_TITLE = 'Security'
export const PROFILE_SETTINGS_TAB_TITLE = 'Settings'
export const PROFILE_ACCESS_TAB_TITLE = 'Access Management'
export const PROFILE_BACK_TO_APPLICATION = 'Back to Application'

export const PROFILE_HOME_TITLE = 'What would you like to do next?'
export const PROFILE_HOME_ORDERING_TITLE = 'Ordering'
export const PROFILE_HOME_CUSTOMER_TITLE = 'Customer'
export const PROFILE_HOME_PARTNER_TITLE = 'Partner'
export const PROFILE_HOME_SUPPLY_TITLE = 'Supply Chain'
export const PROFILE_HOME_ORDERING_DESC = 'Order services directly through our global network of certified partners.'
export const PROFILE_HOME_CUSTOMER_DESC= 'Associate your account with a contract number or bill-to ID.'
export const PROFILE_HOME_PARTNER_DESC_1 = 'Associate your account with a partner company or '
export const PROFILE_HOME_PARTNER_DESC_2 = 'register your company as a partner.'
export const PROFILE_HOME_SUPPLY_DESC = 'Access Supply Chain tools and resources.'
export const PROFILE_HOME_ORDERING_LABEL = 'Go to Ordering'
export const PROFILE_HOME_CUSTOMER_LABEL = 'Go to Customer Portal'
export const PROFILE_HOME_PARTNER_LABEL = 'Go to Partner Self Service'
export const PROFILE_HOME_SUPPLY_LABEL = 'Go to Supply Chain Portal'

export const PROFILE_PERSONAL_DETAILS = 'Your Personal Details'
export const PROFILE_COMPANY_DETAILS = 'Your Company Details'
export const PROFILE_PERSONAL_LAST_LOGIN = 'Last login: '
export const PROFILE_PERSONAL_MODAL_TITLE = 'How to proceed'
export const PROFILE_PERSONAL_MODAL_DESC_1 = 'According to our records, '
export const PROFILE_PERSONAL_MODAL_DESC_2 = ' isn\'t associated with '
export const PROFILE_PERSONAL_MODAL_DESC_3 = '. From here you can: '
export const PROFILE_PERSONAL_MODAL_PARTNER = 'If you\'re a Channel Partner, please update your email in the Partner Self Service Portal.'
export const PROFILE_PERSONAL_MODAL_MERGER_1 = 'If the new domain should be associated with'
export const PROFILE_PERSONAL_MODAL_MERGER_2 = ', please log a case requesting an email update. If approved, we\'ll update your email address and notify you.'
export const PROFILE_PERSONAL_MODAL_COMPANY_CHANGE = 'If you\'re changing companies, please create a new account. We\'ll link it to this one and help you move your personal information across.'
export const PROFILE_PERSONAL_MODAL_LINKING_ACCOUNT = 'More about linking accounts'
export const PROFILE_PERSONAL_MODAL_CHECK_YOUR_EMAIL = 'Check your email'
export const PROFILE_PERSONAL_MODAL_CHECK_YOUR_EMAIL_DESC_1 = "You've changed your email to:"
export const PROFILE_PERSONAL_MODAL_CHECK_YOUR_EMAIL_DESC_2 = "To verify this change, we've sent a verification email to your new address. Please click the button in the mail and sign in, using your new email address to continue."
export const PROFILE_PERSONAL_MODAL_RESEND_EMAIL = "Didn't get the verification email?"
export const PROFILE_PERSONAL_MODAL_RESEND_TEXT = "Resend it"
export const PROFILE_PERSONAL_CHANGE_SITE_ADDRESS = 'Change Site Address'
export const PROFILE_PERSONAL_CURRENT_SITE_ADDRESS = 'Current Site Address'
export const PROFILE_PERSONAL_NO_SITE_ADDRESS = 'No current site address'
export const PROFILE_PERSONAL_NEW_SITE_ADDRESS = 'New Site Address'
export const PROFILE_PERSONAL_NEW_SITE_ADDRESS_DESC = 'If you enter a new address, we have to validate it. Your access to Cisco services may be temporarily impacted.'

export const PROFILE_SECURITY_TITLE = 'Account Security'
export const PROFILE_SECURITY_RECOVERY_NUMBER= 'Recovery Number'
export const PROFILE_SECURITY_RECOVERY_NUMBER_STATEMENT= 'Receive a text to recover account access'
export const PROFILE_SECURITY_2SA = 'Two-Step Authentication'
export const PROFILE_SECURITY_2SA_STATEMENT = 'Ensure that only you can access your account'
export const PROFILE_SECURITY_PASSWORD = 'Password'
export const PROFILE_SECURITY_DISABLE_RECOVERY = `Disabling Recovery Number will remove saved information and would require setup again.`
export const PROFILE_SECURITY_PASSWORD_REQUIRED = 'Password required'
export const PROFILE_SECURITY_PASSWORD_REQUIRED_DESC = 'For security purposes, we need to verify your identity by entering your password below'
export const PROFILE_SECURITY_RECOVERY_SETUP = 'Phone number setup'
export const PROFILE_SECURITY_RECOVERY_SETUP_DESC = 'Enter a phone number you would like to use'
export const PROFILE_SECURITY_RECOVERY_CODE_VERIFY = 'Code Verify'
export const PROFILE_SECURITY_RECOVERY_CODE_VERIFY_DESC = 'For security purposes, we need to verify your identity by entering your received code below'
export const PROFILE_SECURITY_RECOVERY_RESEND = 'Resend the code'
export const PROFILE_SECURITY_RECOVERY_SETUP_FINISHED = 'Phone number verified'
export const PROFILE_SECURITY_RECOVERY_SETUP_FINISHED_DESC = 'Your recovery number is now setup in your account.'
export const PROFILE_SECURITY_DISABLE_2SA_DESC_1 = 'Disabling Two-Step Anthentication will remove all saved information and would require setup again.'
export const PROFILE_SECURITY_DISABLE_2SA_DESC_2 = 'Are you sure you would like to continue?'
export const PROFILE_SECURITY_2SA_STEP1 = 'Step 1 of 2 (Optional)'
export const PROFILE_SECURITY_2SA_STEP1_DESC = 'Select the authentication app(s) to install on your mobile device. If you already have one of these apps installed on your device, click the next button.'
export const PROFILE_SECURITY_2SA_STEP2_DESC = 'Use the authentication app you installed to scan this QR Code.'
export const PROFILE_SECURITY_2SA_STEP1_CLICK_NEXT = 'Once you\'re done installing the app, click on "Next"'
export const PROFILE_SECURITY_2SA_DOWNLOAD_APP = 'Enter your Mobile Number to receive a link to download the app'
export const PROFILE_SECURITY_2SA_STEP2 = 'Step 2 of 2'
export const PROFILE_SECURITY_2SA_STEP2_DESC_2 = 'Enter the key below for manual enrollment.'
export const PROFILE_SECURITY_2SA_TITLE = 'Enroll in Two-Step Authentication'
export const PROFILE_SECURITY_2SA_DESC = 'To enroll in Two-Step Authentication, please follow the below steps.'
export const PROFILE_SECURITY_2SA_SETUP_FINISHED = 'Enrollment Completed!'
export const PROFILE_SECURITY_2SA_SETUP_FINISHED_DESC = 'Two-step authentication is now added to your account.'
export const PROFILE_SECURITY_2SA_SETUP_FINISHED_DESC1 = 'Add an extra layer of security for your Cisco account. This helps ensure that you\'re the only person who can access the account, even if someone knows your password.'
export const PROFILE_SECURITY_2SA_SETUP_FINISHED_DESC2 = 'Select the app store that applies to your device for detailed instructions.'
export const PROFILE_SECURITY_LAST_CHANGED = 'Last changed: '
export const PROFILE_SECURITY_2SA_CODE = 'Your anthentication app will generate a 6-digit code.'
export const PROFILE_SECURITY_APP_GOOGLE = "Google Authenticator"
export const PROFILE_SECURITY_APP_VIP = "Symantec Vip"
export const PROFILE_SECURITY_APP_AUTHY = "Authy Anthenticator"

export const PROFILE_SETTINGS_TITLE = 'Communications';

export const UPDATE_TO_YOUR_PROFILE = "Updates to your Profile";
export const UPDATE_YOUR_PROFILE_DESC = "Your profile changes are undergoing review. We're sorry that you won't be able to make any additional changes while you wait. As soon as we're done, we'll email you. It shouldn't be more than 24 hours.";

export const ACTIVE_ACCOUNT_PAGE_TITLE = 'Profile Management';
export const ACTIVE_ACCOUNT_EMAIL_VERIFIED = 'Email verified';
export const ACTIVE_ACCOUNT_DESCRIPTION = 'You can now access all your available Cisco products and/or services.';
export const ACTIVE_ACCOUNT_LINK_EXPIRED = 'Link expiry';
export const ACTIVE_ACCOUNT_LINK_EXPIRED_DESCRIPTION = 'Your account activation link has expired. Try re-sending the activation email or if you have already activated your account, please sign in.';
export const ACTIVE_ACCOUNT_RETURN = 'Sign in to return to';
export const ACTIVE_ACCOUNT_FULL_STOP = '.';
