const SCOPE_IAM_AUTHMODALITY_DELETE = "/iam.authmodality.delete"
const SCOPE_IAM_AUTHMODALITY_INIT = "/iam.authmodality.init"
const SCOPE_IAM_AUTHMODALITY_MODIFY = "/iam.authmodality.modify"
const SCOPE_IAM_AUTHMODALITY_NOTIFY = "/iam.authmodality.notify"
const SCOPE_IAM_AUTHMODALITY_READER = "/iam.authmodality.reader"
const SCOPE_IAM_AUTHMODALITY_REGISTER = "/iam.authmodality.register"
const SCOPE_IAM_AUTHMODALITY_VERIFY = "/iam.authmodality.verify"
const SCOPE_IAM_VERIFY_PASSWORD = "/iam.verify.password"
const SCOPE_IAM_USER_UNLOCK = "/iam.user.unlock"

const SCOPE_IAM_AUTHMODALITIES_READER = "/iam.authmodalities.reader"

const SCOPE_USERS_AUTHMODALITY_DELETE = "/users.authmodality.delete"
const SCOPE_USERS_AUTHMODALITY_MODIFY = "/users.authmodality.modify"
const SCOPE_USERS_AUTHMODALITY_READ = "/users.authmodality.read"

const SCOPE_USERS_ADMIN = "/users.admin"
const SCOPE_USERS_CREATE = "/users.create"
const SCOPE_USERS_DELETE = "/users.delete"
const SCOPE_USERS_MODIFY = "/users.modify"
const SCOPE_USERS_READ = "/users.read"
const SCOPE_USERS_SEARCH = "/users.search"

const SCOPE_GROUPS_OFFERING_ASSIGNUSERS = "/groups.offering.assignusers"
const SCOPE_GROUPS_OFFERING_CREATE = "/groups.offering.create"
const SCOPE_GROUPS_OFFERING_DELETE = "/groups.offering.delete"
const SCOPE_GROUPS_OFFERING_MODIFY = "/groups.offering.modify"
const SCOPE_GROUPS_OFFERING_READ = "/groups.offering.read"
const SCOPE_GROUPS_OFFERING_SEARCH = "/groups.offering.search"

const SCOPE_GROUPS_PERMISSIONS_ASSIGNUSERS = "/groups.permissions.assignusers"
const SCOPE_GROUPS_PERMISSIONS_CREATE = "/groups.permissions.create"
const SCOPE_GROUPS_PERMISSIONS_DELETE = "/groups.permissions.delete"
const SCOPE_GROUPS_PERMISSIONS_MODIFY = "/groups.permissions.modify"
const SCOPE_GROUPS_PERMISSIONS_READ = "/groups.permissions.read"
const SCOPE_GROUPS_PERMISSIONS_SEARCH = "/groups.permissions.search"

const SCOPE_GROUPS_TENANT_ASSIGNUSERS = "/groups.tenant.assignusers"
const SCOPE_GROUPS_TENANT_CREATE = "/groups.tenant.create"
const SCOPE_GROUPS_TENANT_DELETE = "/groups.tenant.delete"
const SCOPE_GROUPS_TENANT_MODIFY = "/groups.tenant.modify"
const SCOPE_GROUPS_TENANT_READ = "/groups.tenant.read"
const SCOPE_GROUPS_TENANT_SEARCH = "/groups.tenant.search"

const SCOPE_SPTR = "Sptr"

const SCOPE_SETUP_RECOVERY = "/setup.recovery"

const SCOPE_TENANTS_CREATE = "/tenants.create"
const SCOPE_TENANTS_DELETE = "/tenants.delete"
const SCOPE_TENANTS_MODIFY = "/tenants.modify"
const SCOPE_TENANTS_READ = "/tenants.read"
const SCOPE_TENANTS_SEARCH = "/tenants.search"

export const globalScopes = [
  SCOPE_IAM_VERIFY_PASSWORD,
  SCOPE_IAM_USER_UNLOCK,
  SCOPE_IAM_AUTHMODALITY_DELETE,
  SCOPE_IAM_AUTHMODALITY_INIT,
  SCOPE_IAM_AUTHMODALITY_MODIFY,
  SCOPE_IAM_AUTHMODALITY_NOTIFY,
  SCOPE_IAM_AUTHMODALITY_READER,
  SCOPE_IAM_AUTHMODALITY_REGISTER,
  SCOPE_IAM_AUTHMODALITY_VERIFY,
  SCOPE_IAM_AUTHMODALITIES_READER
];

export const tenantScopes = [
  SCOPE_IAM_AUTHMODALITIES_READER,
  SCOPE_IAM_AUTHMODALITY_DELETE,
  SCOPE_IAM_AUTHMODALITY_MODIFY,
  SCOPE_IAM_AUTHMODALITY_READER,
  SCOPE_USERS_AUTHMODALITY_DELETE,
  SCOPE_USERS_AUTHMODALITY_MODIFY,
  SCOPE_USERS_AUTHMODALITY_READ,
  SCOPE_USERS_ADMIN,
  SCOPE_USERS_CREATE,
  SCOPE_USERS_DELETE,
  SCOPE_USERS_MODIFY,
  SCOPE_USERS_READ,
  SCOPE_USERS_SEARCH,
  SCOPE_GROUPS_OFFERING_ASSIGNUSERS,
  SCOPE_GROUPS_OFFERING_CREATE,
  SCOPE_GROUPS_OFFERING_DELETE,
  SCOPE_GROUPS_OFFERING_MODIFY,
  SCOPE_GROUPS_OFFERING_READ,
  SCOPE_GROUPS_OFFERING_SEARCH,
  SCOPE_GROUPS_PERMISSIONS_ASSIGNUSERS,
  SCOPE_GROUPS_PERMISSIONS_CREATE,
  SCOPE_GROUPS_PERMISSIONS_DELETE,
  SCOPE_GROUPS_PERMISSIONS_MODIFY,
  SCOPE_GROUPS_PERMISSIONS_READ,
  SCOPE_GROUPS_PERMISSIONS_SEARCH,
  SCOPE_GROUPS_TENANT_ASSIGNUSERS,
  SCOPE_GROUPS_TENANT_CREATE,
  SCOPE_GROUPS_TENANT_DELETE,
  SCOPE_GROUPS_TENANT_MODIFY,
  SCOPE_GROUPS_TENANT_READ,
  SCOPE_GROUPS_TENANT_SEARCH,
  SCOPE_SPTR,
  SCOPE_SETUP_RECOVERY,
  SCOPE_TENANTS_CREATE,
  SCOPE_TENANTS_DELETE,
  SCOPE_TENANTS_MODIFY,
  SCOPE_TENANTS_READ,
  SCOPE_TENANTS_SEARCH
];
